# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Dimitrios Sikeridis
tagline:          'Personal website'
description:      ''
url:              https://dimisik.github.io
baseurl:          /

author:
  name:           'Dimitrios Sikeridis'
  url:            https://github.com/dimisik

# Site Settings
paginate:         7
excerpt_separator: <!--excerpt_ends-->

#Plugins
whitelist:        []
plugins:             [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dimisik/dimisik.github.io

# Collections
collections:
    supplements:
        output: true
    projects:
        output: false
